version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    command: [ "mongod", "--port", "27017" ]




volumes:
  mongo-data:
